version: "3.9"
services:
 useritem-api-service:
  image: r0842949/api-eindproject
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
